### ISSUE TITLE
How to fetch results?

### ISSUE THREAD

**Issue by Fayozjon** [cgarciagl/Firebird-for-Codeigniter#8]
Hello!
Im trying to get some values from table.
I cant fetch even one row

`$this->db2->get('M_BIO')->row();`

Gives empty array.

`var_dump($this->db2)`
gives:
`object(CI_DB_Firebird_result)#80 (8) { ["conn_id"]=> resource(316) of type (Firebird/InterBase link) ["result_id"]=> resource(317) of type (interbase result) ["result_array"]=> array(0) { } ["result_object"]=> array(0) { } ["custom_result_object"]=> array(0) { } ["current_row"]=> int(0) ["num_rows"]=> int(11) ["row_data"]=> NULL }`

Please help,I need some guide for making CRUD actions with CI 2 + Firebird

**Comment by s4kur4** [comment]
can you try this code

$this->db2->get_where('M_BIO', array('id' => $id))->row();
